# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: cloud
name: terraform
version: 2.1.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: Terraform collection for Ansible.
license_file: LICENSE
tags:
  - terraform
  - cloud
  - infrastructure
  - cluster
repository: https://github.com/ansible-collections/cloud.terraform
homepage: https://github.com/ansible-collections/cloud.terraform
issues: https://github.com/ansible-collections/cloud.terraform/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
